export const fragmentBook = `
    book{
        id
        description
        title
        condition
        status
        swaps{
          id
          status
        }
        creator{
          id  
          email
        }
        holder{
          id  
          email
        }
        edition {
          id
          image
          title
          authors
          description
          isbn_10
          isbn_13
        }
    }
`
