export const GetBook = `
  query($id:String!){
    getBook(id:$id){
      book{
        title
        description
        image{
          url
        }
        id
        condition
        status
        creator{
          email
          id
          firstName 
        }
        holder{
          email
          id
          firstName
        }
        expects{
          email
        }
      }
    }
  }
  `